PRIM_WALLET = {'BECH32': "ZIL_WALLET_PRIM_PUBLIC_ADD_BECH32",
               'PASSWORD': 'ZIL_WALLET_PASSWORD',
               'KEYSTORE': 'ZIL_WALLET_PRIM_KEYSTORE'}

SEC_WALLET = {'BECH32': "ZIL_WALLET_SEC_PUBLIC_ADD_BECH32",
              'PASSWORD': 'ZIL_WALLET_PASSWORD',
              'KEYSTORE': 'ZIL_WALLET_SEC_KEYSTORE'}

THI_WALLET = {'BECH32': "ZIL_WALLET_THI_PUBLIC_ADD_BECH32",
              'PASSWORD': 'ZIL_WALLET_PASSWORD',
              'KEYSTORE': 'ZIL_WALLET_THI_KEYSTORE'}

BIN_WALLET_1_API_1 = {"API_KEY": "BIN_WALLET_1_API_1_KEY",
                      "API_SECRET": "BIN_WALLET_1_API_1_SECRET",
                      "NAME": "BIN_WALLET_1_API_1_NAME",
                      "ACCOUNT_CODE": "BIN_WALLET_1_API_1_ACCOUNT_CODE"}

PERSONAL_ENV_FILE = "PERSONAL_ENV_FILE"

EMAIL_1 = 'EMAIL_1'
EMAIL_1_PASSWORD = 'EMAIL_1_PASSWORD'

EMAIL_2 = 'EMAIL_2'
